version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
  celery:
    user: celery
    build: .
    command: celery -A entrypoint_celery worker --loglevel=info
    env_file:
      - .env.docker
    depends_on:
      - api
      - db
      - redis
  db:
    image: postgres:13
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
