version: '3.8'

services:
  server:
    env_file:
      - .env.docker
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
  worker:
    user: iforger-worker
    build: .
    command: celery -A entrypoint_celery worker --loglevel=info
    env_file:
      - .env.docker
    depends_on:
      - server
      - db
      - cache
  db:
    image: postgres:13
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:6.2
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
