"""empty message

Revision ID: 0964ebc498e7
Revises: 4ae5eef01ada
Create Date: 2021-12-20 09:49:45.430924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0964ebc498e7'
down_revision = '4ae5eef01ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'printers', ['printer_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printers', type_='unique')
    # ### end Alembic commands ###
