"""empty message

Revision ID: 374004cb5621
Revises: e1b6346d33dc
Create Date: 2021-12-22 02:20:11.434071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374004cb5621'
down_revision = 'e1b6346d33dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_ID', sa.Integer(), nullable=True),
    sa.Column('maintenance_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('maintenance_info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['printer_ID'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_logs')
    # ### end Alembic commands ###
