"""empty message

Revision ID: 3810db366574
Revises: c3806fa0bd87
Create Date: 2022-01-02 20:12:13.802403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3810db366574'
down_revision = 'c3806fa0bd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column(
        'filament_usage', sa.Integer(), nullable=True))
    op.drop_column('print_jobs', 'filament')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column(
        'filament', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('print_jobs', 'filament_usage')
    # ### end Alembic commands ###
