"""empty message

Revision ID: 4ae5eef01ada
Revises: 5cee86467675
Create Date: 2021-12-20 09:43:17.263926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae5eef01ada'
down_revision = '5cee86467675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_name', sa.String(length=50), nullable=False),
    sa.Column('printer_type', sa.Enum('ultimaker', 'prusa', name='printer_type'), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('api_key', sa.String(length=50), nullable=True),
    sa.Column('total_timed_printed', sa.Integer(), nullable=True),
    sa.Column('completed_prints', sa.Integer(), nullable=True),
    sa.Column('failed_prints', sa.Integer(), nullable=True),
    sa.Column('total_filament_used', sa.Integer(), nullable=True),
    sa.Column('days_on_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printers')
    # ### end Alembic commands ###
