"""empty message

Revision ID: b6f6d2094994
Revises: 23ecf9960552
Create Date: 2021-12-22 02:29:41.180572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f6d2094994'
down_revision = '23ecf9960552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_logs', sa.Column('printer_id', sa.Integer(), nullable=False))
    op.drop_constraint('maintenance_logs_printer_ID_fkey', 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_logs', 'printers', ['printer_id'], ['id'])
    op.drop_column('maintenance_logs', 'printer_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_logs', sa.Column('printer_ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key('maintenance_logs_printer_ID_fkey', 'maintenance_logs', 'printers', ['printer_ID'], ['id'])
    op.drop_column('maintenance_logs', 'printer_id')
    # ### end Alembic commands ###
