"""empty message

Revision ID: c76037cc2380
Revises: 34c55fa2a910
Create Date: 2022-02-22 12:53:43.170226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76037cc2380'
down_revision = '34c55fa2a910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_added')
    # ### end Alembic commands ###
