"""empty message

Revision ID: f8207b617e17
Revises: b6f6d2094994
Create Date: 2021-12-22 03:14:23.940048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8207b617e17'
down_revision = 'b6f6d2094994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('maintenance_logs_printer_id_fkey', 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_logs', 'printers', ['printer_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key('maintenance_logs_printer_id_fkey', 'maintenance_logs', 'printers', ['printer_id'], ['id'])
    # ### end Alembic commands ###
