"""fix: removed is_queued

Revision ID: 0f06e475d947
Revises: 5c7730ce12ea
Create Date: 2022-12-08 14:57:17.200181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f06e475d947'
down_revision = '5c7730ce12ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('print_jobs', 'is_queued')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column('is_queued', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
