"""empty message

Revision ID: 5c7730ce12ea
Revises: 059f8108256b
Create Date: 2022-12-08 14:08:06.302593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7730ce12ea'
down_revision = '059f8108256b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column('status', sa.Enum('queued', 'approval', 'running', 'complete', 'failed', 'rejected', 'under_review', name='job_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('print_jobs', 'status')
    # ### end Alembic commands ###
