version: '3.8'

services:
  server:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
    env_file:
      - ../.env.docker
    depends_on:
      - db
      - cache
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
  worker:
    user: iforger-worker
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: celery -A entrypoint_celery worker --loglevel=info
    volumes:
      - ..:/app
    env_file:
      - ../.env.docker
    depends_on:
      - server
      - db
      - cache
  db:
    image: postgres:13
    env_file:
      - ../.env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis:6.2
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
