"""empty message

Revision ID: 0a9fcb2eeea6
Revises: 3810db366574
Create Date: 2022-01-02 20:16:02.348605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9fcb2eeea6'
down_revision = '3810db366574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column('printer_type', sa.Enum(
        'ultimaker', 'prusa', name='printer_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('print_jobs', 'printer_type')
    # ### end Alembic commands ###
