"""new Migration

Revision ID: 12bc1a1b93ae
Revises: 3cae1ea6a52f
Create Date: 2022-04-08 17:13:46.039042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bc1a1b93ae'
down_revision = '3cae1ea6a52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_score', sa.Integer(), nullable=True))
    op.drop_column('users', 'user_level')
    op.drop_column('users', 'social_credit_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_credit_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_score')
    # ### end Alembic commands ###
