"""empty message

Revision ID: 453ad556bf8b
Revises: 12bc1a1b93ae
Create Date: 2022-04-08 19:06:26.227758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453ad556bf8b'
down_revision = '12bc1a1b93ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
