"""empty message

Revision ID: c3806fa0bd87
Revises: ebdb21dcef7d
Create Date: 2022-01-02 20:10:49.641110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3806fa0bd87'
down_revision = 'ebdb21dcef7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_jobs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_queued', sa.Boolean(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('print_name', sa.String(
                        length=60), nullable=False),
                    sa.Column('gcode_slug', sa.String(), nullable=False),
                    sa.Column('stl_slug', sa.String(), nullable=True),
                    sa.Column('date_added', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('date_started', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('date_ended', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('colour', sa.String(), nullable=True),
                    sa.Column('upload_notes', sa.String(), nullable=True),
                    sa.Column('queue_notes', sa.String(), nullable=True),
                    sa.Column('checked_by', sa.Integer(), nullable=True),
                    sa.Column('printer', sa.Integer(), nullable=True),
                    sa.Column('project', sa.Enum('personal', 'uni_module',
                                                 'co_curricular', 'other', name='project_types'), nullable=False),
                    sa.Column('project_string', sa.String(), nullable=True),
                    sa.Column('status', sa.Enum('queued', 'accepted', 'approval', 'running', 'complete',
                                                'failed', 'rejected', 'under_review', name='job_status'), nullable=False),
                    sa.Column('print_time', sa.Integer(), nullable=True),
                    sa.Column('filament', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['printer'], ['printers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_jobs')
    # ### end Alembic commands ###
